### PR TITLE
Add support for the AC0850 purifier

### LINKED ISSUE #73: Support Request for Model AC0850
Hi @kongo09, just bought a simple Philips Air Purifier model AC0850. It has 3 modes - Sleep, Auto and Turbo. No other button on the device. In the apps, 2 sensors available for air quality, Allergens (IAI) and PM2.5. Below is the collected raw data for this model for all 3 modes and data when it is turn off from the apps. Tell me if you need any other data for this device. Thanks in advance.

Mode Sleep
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 16929305,
    "rssi": -44,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56392,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 0,
    "D03-05": 0,
    "D03-11": "A",
    "D03-12": "Sleep",
    "D03-13": "s",
    "D03-32": 1,
    "D03-33": 6,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Mode Auto
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17069094,
    "rssi": -46,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56392,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Auto General",
    "D03-13": "1",
    "D03-32": 1,
    "D03-33": 2,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Mode Turbo
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17276669,
    "rssi": -43,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56416,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Turbo",
    "D03-13": "t",
    "D03-32": 1,
    "D03-33": 2,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Device Off
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17376441,
    "rssi": -43,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56416,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "OFF",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Sleep",
    "D03-13": "0",
    "D03-32": 1,
    "D03-33": 5,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

### PR DESCRIPTION
**Pull request by MicSimoen**
Add support for the AC0850 purifier.

I removed the AVAILABLE_LIGHTS = [PHILIPS_NEW_DISPLAY_BACKLIGHT] from the PhilipsNewGenericCoAPFan class as the AC0850/11 doesn't seem to have support to dim the light in the app.

Adding the control to dim the light only has some effect when the purifier is in the sleep mode and it returns automatically to low brightness after a few seconds.

Should resolve #73

### CODE REVIEW

**Comment by azuanaa** [comment]
@MicSimoen, I'm testing the branch - so far so good, except for the AC0850, it has no pre-filter, only nanoProtect filter, so the functionality should not be there. Below is the screenshoot from the controller.
image

**Comment by WMKicker** [comment]
I have this with an AC0850/11 and I can confirm that all functions work so far.
Controlling the fans via the presets works. The values of the air quality sensors are correct (IAI and PM2.5) and the status of the NanoProtect filter is also displayed.
As azuanaa mentioned, the AC0850 does not have a pre-filter and so it should not be shown.

**Comment by kongo09** [comment]
Thank you for helping out and adding the new device. I see that you moved the lights to the AC1715, so I guess removing it from the base should not do any harm. And thank you @WMKicker for confirming that this works.

I'll accept the PR now and then will take a look at the pre-filter question.

**Comment by kongo09** [comment]
you might be able to help with the pre-filter question here #81

**Comment by MicSimoen** [comment]
Thanks, sorry for not reacting earlier but I was unable to test the last weeks

**Pull request merged**
