### PR TITLE
feat: Add support for wifi rssi sensor

### PR DESCRIPTION
**Pull request by mrtwnklr**
Add support for wifi rssi sensor.
I have an AC0850/11 and an AC4236. Both are working with this patch.

### CODE REVIEW

**Comment by kongo09** [comment]
Thanks. I've refactored the consts so the PR doesn't work anymore. If you have time to adapt it, I'll merge it in.

**Comment by mrtwnklr** [comment]
I'll take a look in the next week.

**Comment by kongo09** [comment]
Great. If I get to it before, I can do it as well. Should be easy. Maybe we want a changing icon depending on signal strength?

**Comment by kongo09** [comment]
I've added the sensor now and rebuild icon handling, so that the icon changes with RSSI level. Will also add a runtime sensor and then do a new release. Thanks for the inspiration.

**Pull request closed without merging**
